# Generated by Django 5.1.1 on 2024-09-30 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_voice_id_voice_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
