# Generated by Django 5.1.1 on 2024-10-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_voice_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='file_path',
        ),
        migrations.AddField(
            model_name='voice',
            name='file',
            field=models.FileField(default='', upload_to='voices/'),
        ),
    ]
