# Generated by Django 5.1.1 on 2024-10-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_voice_file_path_voice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='file',
            field=models.FileField(null=True, upload_to='voices/'),
        ),
    ]
