# Generated by Django 5.1.1 on 2024-10-05 14:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_voice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='voice',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.generate_uuid4_filename),
        ),
    ]
