# Generated by Django 5.1.1 on 2024-10-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_voice_deleted_at_alter_voice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
