# Generated by Django 5.1.1 on 2024-10-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_voice_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
