# Generated by Django 5.1.1 on 2024-10-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_voice_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='duration',
        ),
        migrations.AddField(
            model_name='voice',
            name='duration_ms',
            field=models.IntegerField(default=0),
        ),
    ]
