# Generated by Django 5.1.1 on 2024-10-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_voice_duration_voice_duration_ms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voice',
            old_name='duration_ms',
            new_name='duration_s',
        ),
    ]
