# Generated by Django 5.1.1 on 2024-11-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_voice_analysed"),
    ]

    operations = [
        migrations.AddField(
            model_name="voice",
            name="request_country",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
